### ISSUE TITLE
Bug parsing CDM13 Cadets Data

### ISSUE THREAD

**Issue by imolloy** [sbustreamspot/sbustreamspot-docker#4] opened 2016-07-19 13:46 UTC
Traceback (most recent call last):
  File "translate_cdm_to_streamspot.py", line 168, in <module>
    pname = read_field(cdm_record_values['properties']['name'],
KeyError: 'name'

**Comment by imolloy** [comment] 2016-07-19 18:06
The data pushed into Kafka was this: https://github.com/cadets/trace-data/blob/master/buildInject/buildinject.json.CDM.bin

**Comment by emaadmanzoor** [comment] 2016-07-20 00:05
The `properties` map in a CADETS record for a `SUBJECT_PROCESS` looks like this:

```
u'properties': {u'exec': u'sshd'}
```

According to the CDM13 AVDL, the properties map contains [arbitrary keys and values](https://git.tc.bbn.com/bbn/ta3-serialization-schema/blob/master/avro/CDM13.avdl#L530-531).

So it is a bad idea to rely on any keys in this map right now, unless it is used carefully as optional metadata.

Parsing with the new TRACE data is buggy because there are UUID's that appear without first appearing as subjects in the stream.

TODO before closing:
- [x] Ensure no regressions in sbustreamspot-train.
- [x] Verify semantic correctness of constructed graphs in sbustreamspot-train.
- [x] Update sbustreamspot-train to use angular similarity (affects scores in PAAS JSON).
- [x] Update sbustreamspot-core to use angular similarity (affects scores in PAAS JSON).

**Comment by emaadmanzoor** [comment] 2016-07-20 02:16
Angular similarity issue fixed: https://github.com/sbustreamspot/sbustreamspot-core/issues/35

**Closed as completed by emaadmanzoor** 2016-07-20 02:16 UTC

**Comment by imolloy** [comment] 2016-07-20 13:41
So it looks like this is the result of bad data that should be raised on the BBN system. Some errors on Faros datasets:
`Faros Skype`:

```
  File "translate_cdm_to_streamspot.py", line 168, in <module>
    pname = read_field(cdm_record_values['properties']['name'],
TypeError: 'NoneType' object has no attribute '__getitem__'
```

`Faros.avro` This is their small dataset

```
  File "translate_cdm_to_streamspot.py", line 353, in <module>
    pid = uuid_to_pid[to_uuid]
KeyError: '93e0bcd078fcf5fb0e62fbe66d67e579'
```

I haven't loaded TRACE yet. The first one could be an error assuming `properties` is always a `map`, while CMD13 allows it to be a `map` or `None`. The second is more likely a bug similar to the TRACE one you mentioned. CADETS mapping to maps and not strings are also not valid CDM13. For the 14-month, as long as you know there's one data provider that is compliant enough for your code, we should be fine.

**Comment by emaadmanzoor** [comment] 2016-07-20 14:01
Thanks for stress-testing this! I have opened up issues with BBN [here](https://git.tc.bbn.com/bbn/ta3-serialization-schema/issues?scope=all&sort=updated_desc&state=opened&utf8=%E2%9C%93&author_id=72&label-name=).

Also, about `Faros.avro`: I think your container has cached the old code, I have commented out reading the `pname` now. Maybe add a temporary `ARG TEMP` just before the `git clone` for sbustreamspot-cdm in the Dockerfile to invalidate the cache and re-clone the code.

**Comment by imolloy** [comment] 2016-07-20 14:10
I thought the same thing and built with `--force-rm`. Looks like that doesn't do what I think it does. :)

**Comment by emaadmanzoor** [comment] 2016-07-20 15:10
Where did you find the FAROS data? I am not able to connect to anything on cs.unm.edu.

**Comment by imolloy** [comment] 2016-07-20 16:38
Ted had pulled down a copy and still had it on his laptop. Apparently cs.unm.edu is undergoing maintenance. Not sure when it will be back.
